include: package:lint/analysis_options_package.yaml

analyzer:
  exclude:
    - lib/features/residents/models/residents_response.g.dart
  errors:
    todo: warning

linter:
  rules:
    sort_pub_dependencies: false
    prefer_if_elements_to_conditional_expressions: false
